databases:
  - name: Burak
    databaseName: burak
    user: burak_user

services:
  - type: web
    name: nice-car-back-and
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: burak
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false